language: python
python:
  - '2.7'
addons:
  sauce_connect: true
env:
  global:
      - secure: "IFkU1stTDt34cs+BtuGulzogobPzQvO0MWMHDWT5cY4hWrFzxShZbcGueRQCvbyjrEiY2vQ0VX6KCYxUj9neNz90tbW2P9cCURrielkPRVhHorD8ngOtSeknLyzw0UjcBPwigszkFskoqRLPG7p8sa+RJvA+qEsbPr1Jfs0tEgA="
      - secure: "fUdKTZ+nB29tQzKTs5/UnxUc2rm3fkIR31vcm0wFDGhdqMu5K+eZss0qXLrQ7s13JUB8POk8C2juuzJFPiM5yiR1Euhp6RddU6UqLnCaqkV9RH4Y7PjmfpSBgJKi2pOIneRngoOBI0kG6iWjK6f3D7Bb8c94bLbU3ZwGxQLoSkI="
  matrix:
    - DRF_VERSION=">=2.3,<2.4" DJANGO_VERSION=">=1.4,<1.5" MODEL_UTILS_VERSION=">2.0"
    - DRF_VERSION=">=2.3,<2.4" DJANGO_VERSION=">=1.5,<1.6" MODEL_UTILS_VERSION="==1.5"
    - DRF_VERSION=">=2.3,<2.4" DJANGO_VERSION=">=1.6,<1.7" MODEL_UTILS_VERSION=">2.0"
install:
  - pip install wheel setuptools -U
  - pip install Django$DJANGO_VERSION djangorestframework$DRF_VERSION django-model-utils$MODEL_UTILS_VERSION --use-wheel
  - pip install . --use-mirrors --use-wheel
  - pip install -r requirements.txt --use-mirrors --use-wheel
script:
  - make travis
after_success:
  - coveralls
